language: go
sudo: false
go:
    - 1.6.x
      arch: amd64
    - 1.7.x
      arch: amd64
    - 1.8.x
      arch: amd64
    - 1.9.x
      arch: amd64
    - 1.10.x
      arch: amd64
    - 1.11.x
      arch: amd64
    - tip
      arch: amd64
    - 1.6.x
      arch: ppc64le
    - 1.7.x
      arch: ppc64le
    - 1.8.x
      arch: ppc64le
    - 1.9.x
      arch: ppc64le
    - 1.10.x
      arch: ppc64le
    - 1.11.x
      arch: ppc64le
    - tip
      arch: ppc64le
      
matrix:
    allow_failures:
        - go: tip
          arch: amd64
        - go: tip
          arch: ppc64le
    fast_finish: true
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
    email: false
